// Code generated by protoc-gen-go. DO NOT EDIT.
// source: manage.proto

package manage

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PeerRequest struct {
	Count                int32    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeerRequest) Reset()         { *m = PeerRequest{} }
func (m *PeerRequest) String() string { return proto.CompactTextString(m) }
func (*PeerRequest) ProtoMessage()    {}
func (*PeerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_519fa8ed5ffbbc8f, []int{0}
}

func (m *PeerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerRequest.Unmarshal(m, b)
}
func (m *PeerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerRequest.Marshal(b, m, deterministic)
}
func (m *PeerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerRequest.Merge(m, src)
}
func (m *PeerRequest) XXX_Size() int {
	return xxx_messageInfo_PeerRequest.Size(m)
}
func (m *PeerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PeerRequest proto.InternalMessageInfo

func (m *PeerRequest) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type PeerResponse struct {
	Addr                 string   `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Rank                 int32    `protobuf:"varint,2,opt,name=rank,proto3" json:"rank,omitempty"`
	Last                 int64    `protobuf:"varint,3,opt,name=last,proto3" json:"last,omitempty"`
	Server               bool     `protobuf:"varint,4,opt,name=server,proto3" json:"server,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeerResponse) Reset()         { *m = PeerResponse{} }
func (m *PeerResponse) String() string { return proto.CompactTextString(m) }
func (*PeerResponse) ProtoMessage()    {}
func (*PeerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_519fa8ed5ffbbc8f, []int{1}
}

func (m *PeerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerResponse.Unmarshal(m, b)
}
func (m *PeerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerResponse.Marshal(b, m, deterministic)
}
func (m *PeerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerResponse.Merge(m, src)
}
func (m *PeerResponse) XXX_Size() int {
	return xxx_messageInfo_PeerResponse.Size(m)
}
func (m *PeerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PeerResponse proto.InternalMessageInfo

func (m *PeerResponse) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *PeerResponse) GetRank() int32 {
	if m != nil {
		return m.Rank
	}
	return 0
}

func (m *PeerResponse) GetLast() int64 {
	if m != nil {
		return m.Last
	}
	return 0
}

func (m *PeerResponse) GetServer() bool {
	if m != nil {
		return m.Server
	}
	return false
}

type ChainRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChainRequest) Reset()         { *m = ChainRequest{} }
func (m *ChainRequest) String() string { return proto.CompactTextString(m) }
func (*ChainRequest) ProtoMessage()    {}
func (*ChainRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_519fa8ed5ffbbc8f, []int{2}
}

func (m *ChainRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChainRequest.Unmarshal(m, b)
}
func (m *ChainRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChainRequest.Marshal(b, m, deterministic)
}
func (m *ChainRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainRequest.Merge(m, src)
}
func (m *ChainRequest) XXX_Size() int {
	return xxx_messageInfo_ChainRequest.Size(m)
}
func (m *ChainRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChainRequest proto.InternalMessageInfo

func (m *ChainRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ChainResponse struct {
	Ref                  int64    `protobuf:"varint,1,opt,name=ref,proto3" json:"ref,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Count                uint64   `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChainResponse) Reset()         { *m = ChainResponse{} }
func (m *ChainResponse) String() string { return proto.CompactTextString(m) }
func (*ChainResponse) ProtoMessage()    {}
func (*ChainResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_519fa8ed5ffbbc8f, []int{3}
}

func (m *ChainResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChainResponse.Unmarshal(m, b)
}
func (m *ChainResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChainResponse.Marshal(b, m, deterministic)
}
func (m *ChainResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainResponse.Merge(m, src)
}
func (m *ChainResponse) XXX_Size() int {
	return xxx_messageInfo_ChainResponse.Size(m)
}
func (m *ChainResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChainResponse proto.InternalMessageInfo

func (m *ChainResponse) GetRef() int64 {
	if m != nil {
		return m.Ref
	}
	return 0
}

func (m *ChainResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ChainResponse) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type BlockRequest struct {
	ChainID              string   `protobuf:"bytes,1,opt,name=chainID,proto3" json:"chainID,omitempty"`
	From                 uint64   `protobuf:"varint,2,opt,name=from,proto3" json:"from,omitempty"`
	To                   uint64   `protobuf:"varint,3,opt,name=to,proto3" json:"to,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockRequest) Reset()         { *m = BlockRequest{} }
func (m *BlockRequest) String() string { return proto.CompactTextString(m) }
func (*BlockRequest) ProtoMessage()    {}
func (*BlockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_519fa8ed5ffbbc8f, []int{4}
}

func (m *BlockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockRequest.Unmarshal(m, b)
}
func (m *BlockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockRequest.Marshal(b, m, deterministic)
}
func (m *BlockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockRequest.Merge(m, src)
}
func (m *BlockRequest) XXX_Size() int {
	return xxx_messageInfo_BlockRequest.Size(m)
}
func (m *BlockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BlockRequest proto.InternalMessageInfo

func (m *BlockRequest) GetChainID() string {
	if m != nil {
		return m.ChainID
	}
	return ""
}

func (m *BlockRequest) GetFrom() uint64 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *BlockRequest) GetTo() uint64 {
	if m != nil {
		return m.To
	}
	return 0
}

type BlockResponse struct {
	Height               uint64   `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Time                 uint64   `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	PrevHash             string   `protobuf:"bytes,3,opt,name=prevHash,proto3" json:"prevHash,omitempty"`
	Hash                 string   `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"`
	Signature            string   `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	Payload              []byte   `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockResponse) Reset()         { *m = BlockResponse{} }
func (m *BlockResponse) String() string { return proto.CompactTextString(m) }
func (*BlockResponse) ProtoMessage()    {}
func (*BlockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_519fa8ed5ffbbc8f, []int{5}
}

func (m *BlockResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockResponse.Unmarshal(m, b)
}
func (m *BlockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockResponse.Marshal(b, m, deterministic)
}
func (m *BlockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockResponse.Merge(m, src)
}
func (m *BlockResponse) XXX_Size() int {
	return xxx_messageInfo_BlockResponse.Size(m)
}
func (m *BlockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BlockResponse proto.InternalMessageInfo

func (m *BlockResponse) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *BlockResponse) GetTime() uint64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *BlockResponse) GetPrevHash() string {
	if m != nil {
		return m.PrevHash
	}
	return ""
}

func (m *BlockResponse) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *BlockResponse) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *BlockResponse) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type ChainCreationRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Author               string   `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Website              string   `protobuf:"bytes,3,opt,name=website,proto3" json:"website,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Desc                 string   `protobuf:"bytes,5,opt,name=desc,proto3" json:"desc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChainCreationRequest) Reset()         { *m = ChainCreationRequest{} }
func (m *ChainCreationRequest) String() string { return proto.CompactTextString(m) }
func (*ChainCreationRequest) ProtoMessage()    {}
func (*ChainCreationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_519fa8ed5ffbbc8f, []int{6}
}

func (m *ChainCreationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChainCreationRequest.Unmarshal(m, b)
}
func (m *ChainCreationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChainCreationRequest.Marshal(b, m, deterministic)
}
func (m *ChainCreationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainCreationRequest.Merge(m, src)
}
func (m *ChainCreationRequest) XXX_Size() int {
	return xxx_messageInfo_ChainCreationRequest.Size(m)
}
func (m *ChainCreationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainCreationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChainCreationRequest proto.InternalMessageInfo

func (m *ChainCreationRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ChainCreationRequest) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *ChainCreationRequest) GetWebsite() string {
	if m != nil {
		return m.Website
	}
	return ""
}

func (m *ChainCreationRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ChainCreationRequest) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

type ChainCreationResponse struct {
	Ref                  int64    `protobuf:"varint,1,opt,name=ref,proto3" json:"ref,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Wif                  string   `protobuf:"bytes,3,opt,name=wif,proto3" json:"wif,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChainCreationResponse) Reset()         { *m = ChainCreationResponse{} }
func (m *ChainCreationResponse) String() string { return proto.CompactTextString(m) }
func (*ChainCreationResponse) ProtoMessage()    {}
func (*ChainCreationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_519fa8ed5ffbbc8f, []int{7}
}

func (m *ChainCreationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChainCreationResponse.Unmarshal(m, b)
}
func (m *ChainCreationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChainCreationResponse.Marshal(b, m, deterministic)
}
func (m *ChainCreationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainCreationResponse.Merge(m, src)
}
func (m *ChainCreationResponse) XXX_Size() int {
	return xxx_messageInfo_ChainCreationResponse.Size(m)
}
func (m *ChainCreationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainCreationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChainCreationResponse proto.InternalMessageInfo

func (m *ChainCreationResponse) GetRef() int64 {
	if m != nil {
		return m.Ref
	}
	return 0
}

func (m *ChainCreationResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ChainCreationResponse) GetWif() string {
	if m != nil {
		return m.Wif
	}
	return ""
}

type BlockCreationRequest struct {
	ChainID              string   `protobuf:"bytes,1,opt,name=chainID,proto3" json:"chainID,omitempty"`
	Payload              []byte   `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockCreationRequest) Reset()         { *m = BlockCreationRequest{} }
func (m *BlockCreationRequest) String() string { return proto.CompactTextString(m) }
func (*BlockCreationRequest) ProtoMessage()    {}
func (*BlockCreationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_519fa8ed5ffbbc8f, []int{8}
}

func (m *BlockCreationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockCreationRequest.Unmarshal(m, b)
}
func (m *BlockCreationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockCreationRequest.Marshal(b, m, deterministic)
}
func (m *BlockCreationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockCreationRequest.Merge(m, src)
}
func (m *BlockCreationRequest) XXX_Size() int {
	return xxx_messageInfo_BlockCreationRequest.Size(m)
}
func (m *BlockCreationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockCreationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BlockCreationRequest proto.InternalMessageInfo

func (m *BlockCreationRequest) GetChainID() string {
	if m != nil {
		return m.ChainID
	}
	return ""
}

func (m *BlockCreationRequest) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type BlockCreationResponse struct {
	Height               uint64   `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Time                 uint64   `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	PrevHash             string   `protobuf:"bytes,3,opt,name=prevHash,proto3" json:"prevHash,omitempty"`
	Hash                 string   `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"`
	Signature            string   `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockCreationResponse) Reset()         { *m = BlockCreationResponse{} }
func (m *BlockCreationResponse) String() string { return proto.CompactTextString(m) }
func (*BlockCreationResponse) ProtoMessage()    {}
func (*BlockCreationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_519fa8ed5ffbbc8f, []int{9}
}

func (m *BlockCreationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockCreationResponse.Unmarshal(m, b)
}
func (m *BlockCreationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockCreationResponse.Marshal(b, m, deterministic)
}
func (m *BlockCreationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockCreationResponse.Merge(m, src)
}
func (m *BlockCreationResponse) XXX_Size() int {
	return xxx_messageInfo_BlockCreationResponse.Size(m)
}
func (m *BlockCreationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockCreationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BlockCreationResponse proto.InternalMessageInfo

func (m *BlockCreationResponse) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *BlockCreationResponse) GetTime() uint64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *BlockCreationResponse) GetPrevHash() string {
	if m != nil {
		return m.PrevHash
	}
	return ""
}

func (m *BlockCreationResponse) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *BlockCreationResponse) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func init() {
	proto.RegisterType((*PeerRequest)(nil), "manage.PeerRequest")
	proto.RegisterType((*PeerResponse)(nil), "manage.PeerResponse")
	proto.RegisterType((*ChainRequest)(nil), "manage.ChainRequest")
	proto.RegisterType((*ChainResponse)(nil), "manage.ChainResponse")
	proto.RegisterType((*BlockRequest)(nil), "manage.BlockRequest")
	proto.RegisterType((*BlockResponse)(nil), "manage.BlockResponse")
	proto.RegisterType((*ChainCreationRequest)(nil), "manage.ChainCreationRequest")
	proto.RegisterType((*ChainCreationResponse)(nil), "manage.ChainCreationResponse")
	proto.RegisterType((*BlockCreationRequest)(nil), "manage.BlockCreationRequest")
	proto.RegisterType((*BlockCreationResponse)(nil), "manage.BlockCreationResponse")
}

func init() { proto.RegisterFile("manage.proto", fileDescriptor_519fa8ed5ffbbc8f) }

var fileDescriptor_519fa8ed5ffbbc8f = []byte{
	// 527 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x54, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x95, 0x1d, 0x27, 0x24, 0xd3, 0x14, 0x55, 0x4b, 0x52, 0x59, 0x51, 0x41, 0x91, 0xb9, 0xe4,
	0x54, 0x55, 0x70, 0x40, 0xe2, 0x48, 0x10, 0xa1, 0x05, 0x24, 0xe4, 0x3f, 0xd8, 0xc4, 0x93, 0x78,
	0xd5, 0xc4, 0x1b, 0x76, 0x37, 0xad, 0xf8, 0x01, 0xee, 0x7c, 0x03, 0xbf, 0xc4, 0x07, 0xa1, 0x19,
	0xaf, 0x13, 0xc7, 0x6a, 0x25, 0x6e, 0xbd, 0xbd, 0x37, 0xde, 0x79, 0x33, 0xf3, 0x46, 0x63, 0xe8,
	0x6f, 0x64, 0x21, 0x57, 0x78, 0xb9, 0x35, 0xda, 0x69, 0xd1, 0x29, 0x59, 0xf2, 0x1a, 0x4e, 0xbe,
	0x23, 0x9a, 0x14, 0x7f, 0xec, 0xd0, 0x3a, 0x31, 0x80, 0xf6, 0x42, 0xef, 0x0a, 0x17, 0x07, 0xe3,
	0x60, 0xd2, 0x4e, 0x4b, 0x92, 0xcc, 0xa1, 0x5f, 0x3e, 0xb2, 0x5b, 0x5d, 0x58, 0x14, 0x02, 0x22,
	0x99, 0x65, 0x86, 0x1f, 0xf5, 0x52, 0xc6, 0x14, 0x33, 0xb2, 0xb8, 0x8d, 0x43, 0x4e, 0x64, 0x4c,
	0xb1, 0xb5, 0xb4, 0x2e, 0x6e, 0x8d, 0x83, 0x49, 0x2b, 0x65, 0x2c, 0xce, 0xa1, 0x63, 0xd1, 0xdc,
	0xa1, 0x89, 0xa3, 0x71, 0x30, 0xe9, 0xa6, 0x9e, 0x25, 0xaf, 0xa0, 0x3f, 0xcd, 0xa5, 0x2a, 0xaa,
	0x4e, 0x9e, 0x43, 0xa8, 0x32, 0x5f, 0x21, 0x54, 0x59, 0x32, 0x83, 0x53, 0xff, 0xdd, 0x37, 0x71,
	0x06, 0x2d, 0x83, 0x4b, 0x7e, 0xd1, 0x4a, 0x09, 0xfa, 0x94, 0xb0, 0x4a, 0x39, 0x0c, 0x43, 0xf5,
	0xa3, 0x6a, 0x98, 0xaf, 0xd0, 0xff, 0xb0, 0xd6, 0x8b, 0xdb, 0xaa, 0x50, 0x0c, 0xcf, 0x16, 0x24,
	0x7c, 0xfd, 0xd1, 0x57, 0xab, 0x28, 0xb5, 0xbf, 0x34, 0x7a, 0xc3, 0x8a, 0x51, 0xca, 0x98, 0x6a,
	0x38, 0xed, 0x05, 0x43, 0xa7, 0x93, 0x3f, 0x01, 0x9c, 0x7a, 0x39, 0xdf, 0xd7, 0x39, 0x74, 0x72,
	0x54, 0xab, 0xbc, 0xf4, 0x30, 0x4a, 0x3d, 0x23, 0x35, 0xa7, 0x36, 0x58, 0xa9, 0x11, 0x16, 0x23,
	0xe8, 0x6e, 0x0d, 0xde, 0x7d, 0x96, 0x36, 0x67, 0xcd, 0x5e, 0xba, 0xe7, 0xf4, 0x3e, 0xa7, 0x78,
	0x54, 0x9a, 0x4c, 0x58, 0x5c, 0x40, 0xcf, 0xaa, 0x55, 0x21, 0xdd, 0xce, 0x60, 0xdc, 0xe6, 0x0f,
	0x87, 0x00, 0x4d, 0xb2, 0x95, 0x3f, 0xd7, 0x5a, 0x66, 0x71, 0x67, 0x1c, 0x4c, 0xfa, 0x69, 0x45,
	0x93, 0x5f, 0x01, 0x0c, 0xd8, 0xbd, 0xa9, 0x41, 0xe9, 0x94, 0xde, 0xbb, 0x2c, 0x20, 0x2a, 0xe4,
	0x06, 0xab, 0x4d, 0x12, 0xa6, 0x01, 0xe4, 0xce, 0xe5, 0xda, 0x78, 0x2b, 0x3d, 0x23, 0xf9, 0x7b,
	0x9c, 0x5b, 0xe5, 0xd0, 0xf7, 0x5a, 0x51, 0x32, 0x1a, 0x37, 0x52, 0xad, 0x7d, 0xaf, 0x25, 0x21,
	0xed, 0x0c, 0xed, 0xc2, 0xf7, 0xc9, 0x38, 0xf9, 0x02, 0xc3, 0x46, 0x1f, 0xff, 0xbd, 0xcd, 0x33,
	0x68, 0xdd, 0xab, 0xa5, 0x2f, 0x4d, 0x30, 0xb9, 0x81, 0x01, 0x5b, 0xdf, 0x1c, 0xea, 0xf1, 0x8d,
	0xd6, 0x1c, 0x0a, 0x8f, 0x1d, 0xfa, 0x1d, 0xc0, 0xb0, 0x21, 0xf6, 0xd4, 0xfb, 0x7c, 0xf3, 0x37,
	0x84, 0xde, 0xf5, 0xa7, 0xe9, 0x37, 0xbe, 0x54, 0xf1, 0x0e, 0xba, 0x33, 0x74, 0x74, 0x87, 0x56,
	0xbc, 0xb8, 0xf4, 0xc7, 0x5c, 0xbb, 0xdd, 0xd1, 0xe0, 0x38, 0x58, 0xb6, 0x7f, 0x15, 0x88, 0xf7,
	0xd0, 0x9b, 0xa1, 0x63, 0xdb, 0xad, 0xd8, 0x3f, 0xaa, 0x1f, 0xdb, 0x68, 0xd8, 0x88, 0x36, 0x72,
	0xd9, 0x98, 0x5a, 0x6e, 0xfd, 0x7e, 0x0e, 0xb9, 0x47, 0x67, 0x70, 0x15, 0x88, 0x1b, 0x38, 0x61,
	0x33, 0x91, 0x45, 0xc5, 0xc5, 0x51, 0x8d, 0xc6, 0xce, 0x46, 0x2f, 0x1f, 0xf9, 0xea, 0x97, 0xb0,
	0xd7, 0xe2, 0x22, 0x07, 0xad, 0x87, 0xf6, 0x7f, 0xd0, 0x7a, 0x70, 0xa1, 0xf3, 0x0e, 0xff, 0x01,
	0xdf, 0xfe, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x00, 0x63, 0x23, 0x3a, 0x11, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// IFCManageClient is the client API for IFCManage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IFCManageClient interface {
	GetPeers(ctx context.Context, in *PeerRequest, opts ...grpc.CallOption) (IFCManage_GetPeersClient, error)
	GetChains(ctx context.Context, in *ChainRequest, opts ...grpc.CallOption) (IFCManage_GetChainsClient, error)
	GetBlocks(ctx context.Context, in *BlockRequest, opts ...grpc.CallOption) (IFCManage_GetBlocksClient, error)
	CreateChain(ctx context.Context, in *ChainCreationRequest, opts ...grpc.CallOption) (*ChainCreationResponse, error)
	CreateBlock(ctx context.Context, in *BlockCreationRequest, opts ...grpc.CallOption) (*BlockCreationResponse, error)
}

type iFCManageClient struct {
	cc *grpc.ClientConn
}

func NewIFCManageClient(cc *grpc.ClientConn) IFCManageClient {
	return &iFCManageClient{cc}
}

func (c *iFCManageClient) GetPeers(ctx context.Context, in *PeerRequest, opts ...grpc.CallOption) (IFCManage_GetPeersClient, error) {
	stream, err := c.cc.NewStream(ctx, &_IFCManage_serviceDesc.Streams[0], "/manage.IFCManage/GetPeers", opts...)
	if err != nil {
		return nil, err
	}
	x := &iFCManageGetPeersClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type IFCManage_GetPeersClient interface {
	Recv() (*PeerResponse, error)
	grpc.ClientStream
}

type iFCManageGetPeersClient struct {
	grpc.ClientStream
}

func (x *iFCManageGetPeersClient) Recv() (*PeerResponse, error) {
	m := new(PeerResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *iFCManageClient) GetChains(ctx context.Context, in *ChainRequest, opts ...grpc.CallOption) (IFCManage_GetChainsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_IFCManage_serviceDesc.Streams[1], "/manage.IFCManage/GetChains", opts...)
	if err != nil {
		return nil, err
	}
	x := &iFCManageGetChainsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type IFCManage_GetChainsClient interface {
	Recv() (*ChainResponse, error)
	grpc.ClientStream
}

type iFCManageGetChainsClient struct {
	grpc.ClientStream
}

func (x *iFCManageGetChainsClient) Recv() (*ChainResponse, error) {
	m := new(ChainResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *iFCManageClient) GetBlocks(ctx context.Context, in *BlockRequest, opts ...grpc.CallOption) (IFCManage_GetBlocksClient, error) {
	stream, err := c.cc.NewStream(ctx, &_IFCManage_serviceDesc.Streams[2], "/manage.IFCManage/GetBlocks", opts...)
	if err != nil {
		return nil, err
	}
	x := &iFCManageGetBlocksClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type IFCManage_GetBlocksClient interface {
	Recv() (*BlockResponse, error)
	grpc.ClientStream
}

type iFCManageGetBlocksClient struct {
	grpc.ClientStream
}

func (x *iFCManageGetBlocksClient) Recv() (*BlockResponse, error) {
	m := new(BlockResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *iFCManageClient) CreateChain(ctx context.Context, in *ChainCreationRequest, opts ...grpc.CallOption) (*ChainCreationResponse, error) {
	out := new(ChainCreationResponse)
	err := c.cc.Invoke(ctx, "/manage.IFCManage/CreateChain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iFCManageClient) CreateBlock(ctx context.Context, in *BlockCreationRequest, opts ...grpc.CallOption) (*BlockCreationResponse, error) {
	out := new(BlockCreationResponse)
	err := c.cc.Invoke(ctx, "/manage.IFCManage/CreateBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IFCManageServer is the server API for IFCManage service.
type IFCManageServer interface {
	GetPeers(*PeerRequest, IFCManage_GetPeersServer) error
	GetChains(*ChainRequest, IFCManage_GetChainsServer) error
	GetBlocks(*BlockRequest, IFCManage_GetBlocksServer) error
	CreateChain(context.Context, *ChainCreationRequest) (*ChainCreationResponse, error)
	CreateBlock(context.Context, *BlockCreationRequest) (*BlockCreationResponse, error)
}

func RegisterIFCManageServer(s *grpc.Server, srv IFCManageServer) {
	s.RegisterService(&_IFCManage_serviceDesc, srv)
}

func _IFCManage_GetPeers_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PeerRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(IFCManageServer).GetPeers(m, &iFCManageGetPeersServer{stream})
}

type IFCManage_GetPeersServer interface {
	Send(*PeerResponse) error
	grpc.ServerStream
}

type iFCManageGetPeersServer struct {
	grpc.ServerStream
}

func (x *iFCManageGetPeersServer) Send(m *PeerResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _IFCManage_GetChains_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChainRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(IFCManageServer).GetChains(m, &iFCManageGetChainsServer{stream})
}

type IFCManage_GetChainsServer interface {
	Send(*ChainResponse) error
	grpc.ServerStream
}

type iFCManageGetChainsServer struct {
	grpc.ServerStream
}

func (x *iFCManageGetChainsServer) Send(m *ChainResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _IFCManage_GetBlocks_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BlockRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(IFCManageServer).GetBlocks(m, &iFCManageGetBlocksServer{stream})
}

type IFCManage_GetBlocksServer interface {
	Send(*BlockResponse) error
	grpc.ServerStream
}

type iFCManageGetBlocksServer struct {
	grpc.ServerStream
}

func (x *iFCManageGetBlocksServer) Send(m *BlockResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _IFCManage_CreateChain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChainCreationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IFCManageServer).CreateChain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/manage.IFCManage/CreateChain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IFCManageServer).CreateChain(ctx, req.(*ChainCreationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IFCManage_CreateBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlockCreationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IFCManageServer).CreateBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/manage.IFCManage/CreateBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IFCManageServer).CreateBlock(ctx, req.(*BlockCreationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _IFCManage_serviceDesc = grpc.ServiceDesc{
	ServiceName: "manage.IFCManage",
	HandlerType: (*IFCManageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateChain",
			Handler:    _IFCManage_CreateChain_Handler,
		},
		{
			MethodName: "CreateBlock",
			Handler:    _IFCManage_CreateBlock_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetPeers",
			Handler:       _IFCManage_GetPeers_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetChains",
			Handler:       _IFCManage_GetChains_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetBlocks",
			Handler:       _IFCManage_GetBlocks_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "manage.proto",
}
